### ISSUE TITLE
support sql comment

### ISSUE THREAD

**Issue by xxaier** [CeresDB/ceresdb#1017]
### Describe This Problem

<img width="1696" alt="image" src="https://github.com/CeresDB/ceresdb/assets/130831741/b715801f-911b-4e0c-96ec-3c9e17e3b64f">

```
   let fav = r#"CREATE TABLE fav (
    ts TIMESTAMP NOT NULL, // 插入的时间戳
    id uint64 NOT NULL,  // 用户行为的时间戳(毫秒)
    uid uint64 NOT NULL,  // 用户 id
    action uint8 NOT NULL, // 用户行为 : 收藏、取消收藏
    kind uint8 NOT NULL, // 对象类型，比如图片，模型，视频
    rid uint64 NOT NULL, // 收藏对象的 id
    TIMESTAMP KEY(ts),
    PRIMARY KEY(id)
  ) ENGINE=Analytic WITH (
    compression='ZSTD',
    enable_ttl=false
  );
```

### Proposal

as title

**Comment by jiacai2050** [comment]
SQL use `--` character to represent comments, not `//`.

**Comment by zouxiang1993** [comment]
-- as a comment prefix has already supported. 

```
curl --location --request POST 'http://127.0.0.1:5440/sql' --data-ascii '
> SELECT -- some comment
> 1 -- another comment
> '

{"rows":[{"Int64(1)":1}]}% 
```

**Comment by jiacai2050** [comment]
Yes, but partially. 

We haven't store comments, so when you execute `show create table `, comments will be lost.

**Comment by zouxiang1993** [comment]
comment in `show create table` is already supported.

https://github.com/CeresDB/ceresdb/blob/946b3f89e9f6b18c51716a6fe1c5ddb549488dd5/interpreters/src/show_create.rs#L97-L99

**Comment by jiacai2050** [comment]
Oops, it seems we already support this,  and there is a test case for it.

https://github.com/CeresDB/ceresdb/blob/946b3f89e9f6b18c51716a6fe1c5ddb549488dd5/integration_tests/cases/env/local/ddl/create_tables.result#L135

**Comment by jiacai2050** [comment]
@xxaier As said above, current version already support your request, please have a try.
