### ISSUE TITLE
Can I change table write_mode  from "Append" to "Overwrite" dynamically ?

### ISSUE THREAD

**Issue by MachaelLee** [CeresDB/ceresdb#104]
**Which part is this question about**

write_mode
**Describe your question**

Can I change table write_mode  from "Append" to "Overwrite" dynamically ?

**Additional context**

**Comment by waynexia** [comment]
`UpdateMode` is an immutable option that can only be set when `CREATE`ing table: https://github.com/CeresDB/ceresdb/blob/df18e26343da1b29bf4ab8b4f8b8570cd50515a7/analytic_engine/src/table_options.rs#L504-L511

So you cannot change this option dynamically.

**Comment by chunshao90** [comment]
tracked by #156
