### ISSUE TITLE
Row decode out of range

### ISSUE THREAD

**Issue by baojinri** [CeresDB/ceresdb#1097]
### Describe this problem

 Read row out of range 
`2023-07-21 14:35:36.881 ERRO [components/panic_ext/src/lib.rs:42] thread 'ceres-write' panicked 'range start index 1919247122 out of range for slice of length 150' at "common_types/src/row/contiguous.rs:675"
   0: <unknown>
   1: std::panicking::rust_panic_with_hook
   2: <unknown>
   3: <unknown>
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: <unknown>
   7: core::slice::index::slice_start_index_len_fail
   8: <unknown>
   9: common_types::row::contiguous::datum_view_at
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: tokio::runtime::scheduler::multi_thread::worker::run
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: start_thread
  31: clone`

### Server version

After commit: `4a20105bf54c429d7061bc262a0fd72a1a2f75ec`

### Steps to reproduce

Occasional bugs. May occur with a large number of writes and queries.

### Expected behavior

When wirte or query, encode and decode row are fine.

**Comment by ShiKaiWi** [comment]
#1103 may fix this, but I'm not very sure.
