### ISSUE TITLE
Simplify SQL syntax that specifies timestamp key column

### ISSUE THREAD

**Issue by waynexia** [CeresDB/ceresdb#115]
**Description**

`TIMESTAMP KEY` is a special column in analytic engine. It need to be set to a column with `Timestamp` type and with `NOT NULL` constrain.
```sql
CREATE TABLE demo (
    name string TAG,
    value double NOT NULL,
    t timestamp NOT NULL,
    TIMESTAMP KEY(t)
) ENGINE=Analytic;
```

It must have one and only one `TIMESTAMP KEY` column in a table.

**Proposal**
there are a few ways to simplify it.

---------

- Specify `TIMESTAMP KEY` without create a column
Considering the constraints, user is actually giving a name to the `TIMESTAMP KEY` column. 
```sql
CREATE TABLE demo (
    name string TAG,
    value double NOT NULL,
    TIMESTAMP KEY(t)
) ENGINE=Analytic;
```

------------

- Move `TIMESTAMP KEY` to column definition.
This makes `TIMESTAMP KEY` act like primary key.
```sql
CREATE TABLE demo (
    name string TAG,
    value double NOT NULL,
    t timestamp NOT NULL TIMESTAMP KEY
) ENGINE=Analytic;
```

-----------
- Do not need to define it and let CeresDB infers the `TIMESTAMP KEY`
Allow user to not specify `TIMESTAMP KEY` in create table SQL. CeresDB will try to find a column with `Timestamp` type and `NOT NULL`. Report error if zero or multiple columns are found.
```sql
CREATE TABLE demo (
    name string TAG,
    value double NOT NULL,
    t timestamp NOT NULL
) ENGINE=Analytic;
```

**Additional context**

**Comment by dust1** [comment]
I think the second one would be better, `t` appears to be a special kind of primary key? maybe we can create it by creating a primary key?

**Comment by waynexia** [comment]
Yes, the second one is derived from PRIMARY KEY's syntax. One key difference between TIMESTAMP KEY and PRIMARY KEY is that we can only define one TIMESTAMP KEY per table.

**Comment by dust1** [comment]
Does anyone else have a better opinion? maybe I can try to accomplish this first?😃

**Comment by ShiKaiWi** [comment]
Vote for the second proposal. And to keep consistent with primary key syntax in mysql, the `not null` constraint on timestamp key can be made optional too. As for the `timestamp` type, I prefer to make it required.

**Comment by jiacai2050** [comment]
Just want to make sure, if we go with the second approach, the old syntax will be kept as it is now?

**Comment by ShiKaiWi** [comment]
> Just want to make sure, if we go with the second approach, the old syntax will be kept as it is now?

The old syntax should be still supported.
