### ISSUE TITLE
Distinguish the source call's api of grpc

### ISSUE THREAD

**Issue by tanruixiang** [CeresDB/ceresdb#1262]
### Describe This Problem

Different api such as opentsdb are using grpc calls at the bottom, we need to use Context to distinguish the source of grpc in order to perform different operations. For example,in https://github.com/CeresDB/ceresdb/pull/1261  we need to disable the auto create table feature.

### Proposal

Distinguish the source call's api of grpc

**Comment by jiacai2050** [comment]
No need for now.
