### ISSUE TITLE
Show tables statement support name like syntax

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/ceresdb#128]
**Description**

Currently, `show tables` is supported by CeresDB, it would be convenient to support name like syntax like in MySQL.
```
SHOW TABLES LIKE 'pattern'
```

**Proposal**

Support this syntax with reference with MySQL

**Additional context**

Currently it will return error below
- https://github.com/CeresDB/ceresdb/blob/334bc6ce13aac2e72a0771419b4aefe2164255e9/tests/cases/01_system/system_tables.result#L15

ref #154

**Comment by QuintinTao** [comment]
hi， I wonder that we need to support "SHOW TABLES LIKE 'pattern'" or  "SHOW TABLES `name` LIKE '01_system_table1'"?
Is the `name` esential?

**Comment by QuintinTao** [comment]
Thanks I want to try it.

**Comment by QuintinTao** [comment]
> There are [two special chars](https://dev.mysql.com/doc/refman/8.0/en/pattern-matching.html) in `pattern`
> 
> * `_` to match any single character and
> * `%` to match an arbitrary number of characters (including zero characters).
> 
> We can replace `_` to `.` and `%` to `.*` to match regex syntax.

OK
