### ISSUE TITLE
both WeChat and slack links are dead

### ISSUE THREAD

**Issue by zwpaper** [CeresDB/ceresdb#139]
both WeChat and slack links are dead, maybe needs a more effective way to keep the WeChat invitation image active

**Comment by yeya24** [comment]
I think I encountered the same problem. WeChat QR code expired and cannot join Slack via invitation.

**Comment by yeya24** [comment]
It works thank you!

**Comment by yeya24** [comment]
The WeChat qrcode still not working though

**Comment by zwpaper** [comment]
but at least we have one valid way to communicate, I am also waiting for the reply for the QRCode you asked in slack 🤣

**Comment by waynexia** [comment]
Sorry for it. WeChat has been sent in slack, We'll update the link later 😣
