### ISSUE TITLE
replace the python2 entrypoint with shell

### ISSUE THREAD

**Issue by zwpaper** [CeresDB/ceresdb#145]
**Description**

1. python2 retired in 2020, we should not stop the process
2. the entrypoint.py is working on modifying files, exec processes, etc., shell script fits the requirement better
3. both supervisor and tinit are used to keep ceresdb alive, but supervisor is not necessary, docker did the trick

**Proposal**

1. replace entrypoint.py with entrypoint.sh
2. drop supervisor and run ceresDB under tinit directly

**Additional context**

if we reach an agreement on this, I would like to take this job

**Comment by waynexia** [comment]
This sounds good 🚀  Thanks for your help!

**Comment by zwpaper** [comment]
IMHO, if we have multi processes to be managed, supervisor would be a choice(maybe even not a good choice), but ceresDB only has one server process.

as for the management part, Docker containers are meant to be short living, process should be restarted with the container, not inside the container.

as for logging, containers should print to stdout/stderr directly so that the logging service like fluentd, filebeat, could collect them easily in CNCF would.

as for os signal etc., tinit did the trick.

so my suggestion would be to drop it, but we can leave it alone if you insisted.
