### ISSUE TITLE
Document upgrade and downgrade processes

### ISSUE THREAD

**Issue by zamazan4ik** [CeresDB/ceresdb#170]
Hi.

After reading the documentation it is not clear for me, how upgrade and downgrade processes should be performed over the database. Could you please describe somewhere in the documentation:

- How to upgrade the database to the newer version (hopefully with no downtime)
- How to downgrade the database to the older version (hopefully with no downtime)
- Maybe some compatibility policies and notes between versions

Thanks in advance!

**Comment by waynexia** [comment]
Glad you are interested 😃 

Nodes cannot be added or removed "dynamically" in the present version -- you need to replace and restart the entire cluster for upgrading or downgrading. Or in other words, we simply do not support changing versions so we didn't document it.

But this is definitely a key feature, we plan to ship it in the next one or two small milestones (v0.4 or v0.5). This is in the design (in mind) stage, @ShiKaiWi may lay out an RFC about how will CeresDB achieve the cluster mode. Graceful upgrade/downgrade should be included.

And for compatibility, we will do our best to keep backward compatibility in the storage format, and will obey the [Semantic Versioning](https://semver.org/) across all interfaces. If any breaking change is made it will be documented in the version note.

Hope that helps ❤️

**Comment by zamazan4ik** [comment]
@waynexia Thank you! Could you please put this information somewhere into the documentation?

**Comment by waynexia** [comment]
Sure! Sorry for the late reply, I'll document it this morning
