### ISSUE TITLE
Bump sqlparser

### ISSUE THREAD

**Issue by Rachelint** [CeresDB/ceresdb#171]
**Description**

Bump version of sqlparser from 0.18.0 to 0.19.0, some bugs such as #123 can be fixed after doing this. 

**Proposal**
Maybe you have considered some ideas or solutions about this feature.

**Additional context**
Changelogs:
https://github.com/sqlparser-rs/sqlparser-rs/blob/main/CHANGELOG.md

**Comment by waynexia** [comment]
I've updated sqlparser in datafusion [d8184e71589e95b27db0e2c0ce0a8c51a6564c7a](https://github.com/waynexia/arrow-datafusion/commit/d8184e71589e95b27db0e2c0ce0a8c51a6564c7a)
