### ISSUE TITLE
Column order is not what user define when create table

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/ceresdb#187]
### Describe this problem

Table' columns order is not what user define when create table

### Steps to reproduce

Execute those SQL
```sql
CREATE TABLE test_order (
    host string tag,
    v2 int,
    ts timestamp NOT NULL,
    v1 int,
    timestamp KEY (ts)
)ENGINE = Analytic WITH (
    enable_ttl = 'false'
);

desc test_order;
```
`desc` will output 

```
ts	timestamp	1	0	0
tsid	uint64	1	0	0
host	string	0	1	1
v1	int	0	1	1
v2	int	0	1	0
```

### Expected behavior

The column order should be same with the order when created.

### Additional Information

https://github.com/CeresDB/ceresdb/blob/3e826ffbb98d2c5351e63b28dd9dd4644e7d4c1e/sql/src/planner.rs#L265

The root cause is currently we use a BTreeMap when build create table plan, it should use a vector to keep the ordering

ref #154

**Comment by dust1** [comment]
Can we reorder fields by subscripting the fields? like    
https://github.com/CeresDB/ceresdb/blob/5c14f0055fb6816793b81bbc50c61b12b3079d5c/server/src/handlers/sql.rs#L201-L207

**Comment by dust1** [comment]
This looks like the `BTree` needs to be removed, will it infect the storage layer?

**Comment by dust1** [comment]
maybe I can try to fix this, can it be assigned to me?
