### ISSUE TITLE
Should we support `Date` type?

### ISSUE THREAD

**Issue by Rachelint** [CeresDB/ceresdb#194]
### Describe This Problem

`Date` is a common type in database, should we support it ?
Every row here must contain timestamp, `Date` type seems a bit redundant, but some information(such as birthday) seems more appropriate to express by `Date`?

### Proposal

+ Use i32/i64 to store date32/date64 like arrow.
+ Add necessary conversions like other defined types.
+ Format it in response.

**Comment by ShiKaiWi** [comment]
It is great if `Date` is supported, and we can leave this feature for volunteers in the community.

**Comment by impactCn** [comment]
I am try. pls assign me.

**Comment by ShiKaiWi** [comment]
> I am try. pls assign me.

The proposal is a little bit simple, and any discussion is welcome when you have any difficulty in implementing this feature.

**Comment by MachaelLee** [comment]
1. A date. The supported range is '1000-01-01' to '9999-12-31'. MySQL displays [DATE](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) values in 'YYYY-MM-DD' format.See:https://dev.mysql.com/doc/refman/8.0/en/date-and-time-type-syntax.html
2. But permits assignment of values to [DATE](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) columns using either strings or numbers. like: STR_TO_DATE,SUB_DATE,See:https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_str-to-date

**Comment by ShiKaiWi** [comment]
@MachaelLee 
> But permits assignment of values to [DATE](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) columns using either strings or numbers

For such conversion, I guess we already have an example for that -- converting string date literal to timestamp literal.

**Comment by MachaelLee** [comment]
> @MachaelLee
> 
> > But permits assignment of values to [DATE](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) columns using either strings or numbers
> 
> For such conversion, I guess we already have an example for that -- converting string date literal to timestamp literal.

It is not common that converting string date literal to timestamp literal. Usually we convert timestamp to date with ` cast( timestamp as date)`;  sometimes we convert date to unixtimetamp with `UNIX_TIMESTAMP()`, it returns the value of the argument as seconds since '1970-01-01 00:00:00' UTC.
