### ISSUE TITLE
Make RocksDB a conditional dependency

### ISSUE THREAD

**Issue by waynexia** [CeresDB/ceresdb#206]
### Describe This Problem

RocksDB is one of the WAL implementations, also the earliest one. We have to depend on it for everything. It's a great project and does help a lot but it also brings lots of problems like flaky tests #85, long compile time #151 or strange compile problem #16.

And things have changed for now. After #62 we have other WAL implementations like one implemented on mem. It's time to make RocksDB an optional dependency and only compile it when needed.

### Proposal

- Make RocksDB and related code (e.g, tests) optional via feature gate
- Migrate existing tests to the memory impl, so they are still available without RocksDB. The memory impl is inside https://github.com/CeresDB/ceresdb/blob/5bfb5772668fa5f09a4467f476e2146725e7ebe5/wal/src/table_kv_impl/wal.rs#L100 with https://github.com/CeresDB/ceresdb/blob/5bfb5772668fa5f09a4467f476e2146725e7ebe5/components/table_kv/src/memory.rs#L193 [This benchmark](https://github.com/CeresDB/ceresdb/blob/main/benchmarks/src/wal_write_bench.rs) already make use of it.
- Make it a default option on standalone mode.

**Comment by QuintinTao** [comment]
hi，I want to participate this issue. but I am not very clear about those proposals.
1."Make RocksDB and related code (e.g, tests) optional via feature gate"  I can see a conditional in here. 
setup.rs
if config.analytic.obkv_wal.enable {
2.Migrate existing tests to the memory impl, so they are still available without RocksDB. 
which part do you mean?

**Comment by waynexia** [comment]
Greeting! Thanks for your interesting :heart:

>1."Make RocksDB and related code (e.g, tests) optional via feature gate" I can see a conditional in here.
setup.rs
if config.analytic.obkv_wal.enable {

This is one part. But the "conditional" I refer to is rust's [conditional compilation](https://doc.rust-lang.org/reference/conditional-compilation.html). That is, telling the compiler not to compile rocksdb-related code under some condition (e.g., via a feature gate). By doing so we only need to pay for rocksdb's compilation when we needed.

>2.Migrate existing tests to the memory impl, so they are still available without RocksDB.
which part do you mean?

This is another aspect. Current we are using RocksDB to backing some local test cases. But in most situation we don't have to rely on it. One of the main scenario is tests using WAL. We have a WAL implementation in memory which can replace RocksDB to accomplish the test.

Hope I answered your question and feel free to point out any uncertain thing 😉

**Comment by QuintinTao** [comment]
> Greeting! Thanks for your interesting heart
> 
> > 1."Make RocksDB and related code (e.g, tests) optional via feature gate" I can see a conditional in here.
> > setup.rs
> > if config.analytic.obkv_wal.enable {
> 
> This is one part. But the "conditional" I refer to is rust's [conditional compilation](https://doc.rust-lang.org/reference/conditional-compilation.html). That is, telling the compiler not to compile rocksdb-related code under some condition (e.g., via a feature gate). By doing so we only need to pay for rocksdb's compilation when we needed.
> 
> > 2.Migrate existing tests to the memory impl, so they are still available without RocksDB.
> > which part do you mean?
> 
> This is another aspect. Current we are using RocksDB to backing some local test cases. But in most situation we don't have to rely on it. One of the main scenario is tests using WAL. We have a WAL implementation in memory which can replace RocksDB to accomplish the test.
> 
> Hope I answered your question and feel free to point out any uncertain thing wink

Thanks for your patient explanation. Let me try.

**Comment by ShiKaiWi** [comment]
> hi， I want to add features in the wal model. default is rocksdb.
> 
> ```
> [features]
> default = ["rocksdb"]
> rocksdb = []
> tablekv = []
> ```
> 
> then I will mark the code with:
> 
> ```rust
> #[cfg(feature = "rocksdb")]
> #[cfg(feature = "rocksdb")]
> #[derive(Default)]
> pub struct RocksEngineBuilder;
> ```

I guess this is not enough. More things need fixing, including:
- Use the feature gate to control whether to compile `wal/src/rocks_impl` module;
- Use the conditional compilation to control the codes to use memory-wal (you can refer to https://github.com/CeresDB/ceresdb/blob/main/benchmarks/src/wal_write_bench.rs#L68-L74) instead of `wal/src/rocks_impl` if necessary;

**Comment by QuintinTao** [comment]
> > hi， I want to add features in the wal model. default is rocksdb.
> > ```
> > [features]
> > default = ["rocksdb"]
> > rocksdb = []
> > tablekv = []
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then I will mark the code with:
> > ```rust
> > #[cfg(feature = "rocksdb")]
> > #[cfg(feature = "rocksdb")]
> > #[derive(Default)]
> > pub struct RocksEngineBuilder;
> > ```
> 
> I guess this is not enough. More things need fixing, including:
> 
> * Use the feature gate to control whether to compile `wal/src/rocks_impl` module;
> * Use the conditional compilation to control the codes to use memory-wal (you can refer to https://github.com/CeresDB/ceresdb/blob/main/benchmarks/src/wal_write_bench.rs#L68-L74) instead of `wal/src/rocks_impl` if necessary;

I am sorry. I was busy with other things. May continue now?

**Comment by QuintinTao** [comment]
hi, if I use feature gate to cntrol rocks related code.
I use cfg here
![image](https://user-images.githubusercontent.com/72123724/206647283-2b046d89-d0ad-40d7-a5af-71ad9d59754a.png)

 match config.analytic.wal_storage {
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^ pattern `RocksDB` not covered

**Comment by waynexia** [comment]
Does also add this feature gate to this variant in the enum definition work?

**Comment by ShiKaiWi** [comment]
> hi, if I use feature gate to cntrol rocks related code. I use cfg here ![image](https://user-images.githubusercontent.com/72123724/206647283-2b046d89-d0ad-40d7-a5af-71ad9d59754a.png)
> 
> match config.analytic.wal_storage { | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ pattern `RocksDB` not covered

Maybe you should add the feature gate to the definition of WalStorageConfig to control the field `WalStorageConfig::RocksDB`.

**Comment by jiacai2050** [comment]
@QuintinTao Hi, any progress on this issue?

This issue may not easy to deal with, so if you are having any trouble,  you can ask questions here or choose other [good first issues](https://github.com/CeresDB/ceresdb/labels/good%20first%20issue).

**Comment by Rachelint** [comment]
finished in #1222
