### ISSUE TITLE
Sed error while run with docker(use -v to mount config).

### ISSUE THREAD

**Issue by Rachelint** [CeresDB/ceresdb#229]
### Describe this problem

While run our docker image v0.3.0 with mounted config file, an error from `sed` occurred.
It complains `sed: cannot rename /etc/ceresdb/sedYMPxJV: Device or resource busy`.

### Steps to reproduce

+ Run as follow:
```
docker run -d --name ceresdb-server \
  -p 8831:8831 \
  -p 3307:3307 \
  -p 5440:5440 \
  -v your/path/ceresdb/docs/your-config:/etc/ceresdb/ceresdb.toml \
  ceresdb/ceresdb-server:v0.3.0
```
+ Check its running status:
```
docker logs ceresdb-server
```

**Comment by chunshao90** [comment]
I will fix this bug in #230 .
