### ISSUE TITLE
RFC for dynamic routing of CeresDB cluster mode

### ISSUE THREAD

**Issue by ZuLiangWang** [CeresDB/ceresdb#237]
### Describe This Problem

In Release v0.3, we initially implemented the cluster mode of CeresDB and provided static routing based on CeresMeta's initialization.
However, it is obvious that this simple implementation cannot support the dynamic scheduling in distributed scenarios.
Through distributed dynamic routing, we hope to achieve：

- High availability.
- Automatic scheduling of CeresDB computing resources for good load balancing.

### Proposal

Draw an RFC for dynamic routing of CeresDB cluster mode.

**Comment by mrrtree** [comment]
Duplicate with #198
