### ISSUE TITLE
Security: `failure` reports a critical level vulnerability warning

### ISSUE THREAD

**Issue by waynexia** [CeresDB/ceresdb#24]
**Describe this problem**
https://github.com/CeresDB/ceresdb/security/dependabot/2

**Steps to reproduce**
N/A

**Expected behavior**
Fix this warning

**Additional Information**
>An issue was discovered in the failure crate through 2019-11-13 for Rust. Type confusion can occur when private_get_type_id is overridden.

Dependabot doesn't find a patch version fixes this.

**Comment by ShiKaiWi** [comment]
Currently, the very old `failure` crate is only used by obkv client, that is to say, we have to upgrade the dependencies of obkv client.

**Comment by ShiKaiWi** [comment]
Fixed by #701.
