### ISSUE TITLE
add method to flush memtable manually

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/ceresdb#27]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Add method to flush memtable manually

**Description**
Currently memtable flush is controlled by [should_flush_table](https://github.com/ceresdb/CeresDB/blob/33e95a42277fced611ca50d39e4f3541d1555430/analytic_engine/src/table/data.rs#L381), it would be convenient to provide a method to flush memtable explicitly, to release memory pressure or to persist data to underlying objectstore 

**Proposal**
add a HTTP endpoint to flush memtable

**Comment by evenyag** [comment]
Seems `Table` supports [manual flush](https://github.com/CeresDB/ceresdb/blob/8667e4c9859ce3b5fd04e075add05ec154e4f7c6/table_engine/src/table.rs#L457) , maybe the HTTP endpoint can just call `Table::flush()`.

**Comment by waynexia** [comment]
> Seems `Table` supports [manual flush](https://github.com/CeresDB/ceresdb/blob/8667e4c9859ce3b5fd04e075add05ec154e4f7c6/table_engine/src/table.rs#L457) , maybe the HTTP endpoint can just call `Table::flush()`.

That sounds good! :+1:  Would you like to submit a Pull Request @evenyag ?

**Comment by jiacai2050** [comment]
Thanks for your interest, I have started this feature in my forked repo, maybe you can try other issues first. 
- https://github.com/jiacai2050/ceresdb/commits/feat-flush-memtable
