### ISSUE TITLE
Avoid data copy in parquet reader.

### ISSUE THREAD

**Issue by chunshao90** [CeresDB/ceresdb#273]
### Describe This Problem

After parquet is upgraded by #269, some api changes and in order to adapt them some performance issues are introduced:
https://github.com/CeresDB/ceresdb/blob/a8fb2c92edb979051fbfbd339d72f65f94628f2c/components/parquet_ext/src/serialized_reader.rs#L195-L202

### Proposal
(TODO)

**Comment by ShiKaiWi** [comment]
I guess this has been fixed already.
