### ISSUE TITLE
CI failed sometimes caused by no space left

### ISSUE THREAD

**Issue by ygf11** [CeresDB/ceresdb#299]
### Describe this problem

CI failed sometimes caused by no space left.

see the action: https://github.com/CeresDB/ceresdb/actions/runs/3238830826

### Steps to reproduce

It happens sometimes.

**Comment by ShiKaiWi** [comment]
Actually, the target directory will increase a little after one ci runs. What we need may be a mechanism to auto clean the target directory when the decompressed target directory is too large.

**Comment by ygf11** [comment]
Maybe we can remove `target` from cache, this will slow down the execution of CI.

So we need test if it is tolerable.

**Comment by ShiKaiWi** [comment]
> Maybe we can remove `target` from cache, If the execution of CI will not slow down too much.

Actually, the cache matters a lot in speeding up CI. #301 has fixed this issue.
