### ISSUE TITLE
Disallow defining timestamp key column  as Tag column

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/ceresdb#354]
### Describe this problem

Now we can define the timestamp key column as tag column, but that is totally meaningless and leads to bad performance.

### Steps to reproduce

Execute the sql to create a table:
```sql
CREATE TABLE IF NOT EXISTS demo (
    name string TAG,
    value double,
    t timestamp NOT NULL TAG,
    TIMESTAMP KEY(t)) ENGINE=Analytic with (enable_ttl=false);
```

### Expected behavior

It should fail rather than succeed.

**Comment by QuintinTao** [comment]
hi, I think I can do it.
I will add an user-define error like this.
  #[snafu(display("Timestamp column can not be Tag, name:{}", name))]
    TimestampColumnCanNotTag { name: String },
and
add check in create_table_to_plan
like this.
 if name_column_map.get(&timestamp_name as &str).is_some() {
            ensure!(
                    !name_column_map.get(&timestamp_name as &str).unwrap().is_tag,
                    TimestampColumnCanNotTag {
                        name: &timestamp_name as &str,
                    }
            )
        }

**Comment by ShiKaiWi** [comment]
@QuintinTao Your proposal is great. It will be appreciated if you can make such contribution.
