### ISSUE TITLE
Enhance cache for OSS storage

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/ceresdb#391]
### Describe This Problem

Currently, we have `DataCache` & `MetaCache` for underlying storage to speed up the query process, and specifically, for OSS storage, a disk cache with size limit is designed for a larger capacity. However, there are still some issues concerning the current cache design, leading to poor performance of query:
- It costs too much CPU and takes long time to decode the custom metadata (including bloom filters, time range of sst) encoded as extended key value pairs in the parquet footer.
- The memory cache has only a limit on the entry number, and no limit on the size, that is to say, such a cache may need much tuning to make it perform best for the user's data pattern and the memory capacity of the machine on which ceresdb is deployed.

### Proposal

To solve the two issues about the current cache design, I propose:
- Add cache for both custom metadata and parquet metadata, to avoid extra decoding procedure for our custom metadata. #392
- Refactor memory data cache to make it featured with size limit, and integrated into the `object_store` module in order to combine it with disk cache to serve as a two-tier cache.

**Comment by jiacai2050** [comment]
- https://github.com/facebook/rocksdb/wiki/Block-Cache

There  are two kinds of cache used in RocksDB, LRU and Clock.

LRU is simple to start with, so I plan to implement one based on https://github.com/jiacai2050/lru-weighted-cache.

Key is `${sst-path}-${range}`, value is bytes, also this cache will support shard to reduce lock contention

**Comment by jiacai2050** [comment]
There will be two kinds of caches: one is memory, the other is disk. 

Both is limited by `capacity` configured when started, and use lru to evict inactive ones.

# Memory

    range = [start_offset, end_offset)
    key = sst_id + range
    value = bytes


# Disk

    key = sst_id + align_range(named blocks)
    value = bytes

`align_range` is used for reduce file number in case when range is too small,
and a get request's range will be split into multiple blocks.

For example, when `align_range` is 4KB, then a get request `(4000, 5000)` will cause
the both `[0, 4096)` and `[4096, 8192)` to be cached,

**Comment by Rachelint** [comment]
Maybe memory cache should be aligned?

**Comment by jiacai2050** [comment]
https://github.com/tikv/rocksdb/blob/0b1b80c4927bccbf0b318cdbd9cde6a1e563ae6f/cache/lru_cache.cc#L356

RocksDB's cache is not align, I think advantage of aligned range for memory is not obvious, if it's aligned, then the align unit will much smaller than disk's, which may result in multiple requests for request with large range.

So I guess we can firstly implement memory cache unaligned, then to check how it works for real workload.
