### ISSUE TITLE
Migrate current harness tests to sqlness

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/ceresdb#397]
### Describe This Problem

[sqlness](https://github.com/CeresDB/sqlness) has been created as a separated repo, but ceresdb doesn't use it now.

### Proposal

Let's migrate the harness tests to the sqlness.

**Comment by jiacai2050** [comment]
There is no docs for sqlness, so this may not very friendly for volunteers...

**Comment by dust1** [comment]
maybe I can do it. Can you assign it to me?

**Comment by jiacai2050** [comment]
Yeah, go ahead.

There is a [pending PR](https://github.com/CeresDB/ceresdb/pull/388) to update client, we will merge this soon, you can first figure out how to use sqlness framework since there are no docs for it.

**Comment by dust1** [comment]
> 

ok, I will create a new project to using `sqlness`.

**Comment by ShiKaiWi** [comment]
> > 
> 
> ok, I will create a new project to using `sqlness`.

Actually, `sqlness` is almost same as the codes in the https://github.com/CeresDB/ceresdb/tree/main/tests/harness, maybe there is no need to create a new project?

**Comment by dust1** [comment]
> Actually, `sqlness` is almost same as the codes in the https://github.com/CeresDB/ceresdb/tree/main/tests/harness, maybe there is no need to create a new project?

yes, I mean i will try `sqlness` in another new project before this pr merge

**Comment by jiacai2050** [comment]
@dust1  I have bump client to latest version in this PR https://github.com/CeresDB/ceresdb/pull/409, so there is nothing blocking this.

**Comment by waynexia** [comment]
> There is no docs for sqlness, so this may not very friendly for volunteers...

Currently, it only contains docs within the doc comment (`///`). Since this crate is not published yet, you need to run `cargo doc --open` to open it 🥲 Not very convenient but it should be better after our first publish.

**Comment by jiacai2050** [comment]
Got it, I will try to publish to crates.io when #473 is finished(ensure everything works as expected, and used for demonstration).

**Comment by dust1** [comment]
Do you need to add a new environment if you want to demonstrate? Currently only `local`

**Comment by jiacai2050** [comment]
Multiple envs demo is required before publish, we can add it in sqlness repo. 

We can create a demo project here, such as 
```
$tree examples/
examples/
├── distributed
│   └── select.sql
└── local
    └── select.sql

```
