### ISSUE TITLE
Potential API/storage format breaking change

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/ceresdb#402]
### Describe This Problem

When release 1.0, breaking change is not acceptable, so we need to 
1. Remove bad design 
2. Add compatible method to old format 

This issue is mainly used to collect potential breaking changes

### Proposal

As above

### Additional Context

Some examples I can think of
- #321, we need to record sst file size in manifest;
- #340;
- #495 Define the custom format for SST;

**Comment by ShiKaiWi** [comment]
What I can come up with now includes:
- Define the custom format for SST (now it is totally a parquet file) for the possible brand-new format in the future;
- Refactor the manifest implementation because current one is complicated and may not work well with OBKV;

**Comment by ShiKaiWi** [comment]
One more thing deserved mentioning here, currently the protocol maps the tenant to the schema, which is actually reasonable actually.

**Comment by jiacai2050** [comment]
- rename NumKeyColumns to PrimaryKeyIndexes https://github.com/CeresDB/ceresdb/pull/526

**Comment by ShiKaiWi** [comment]
https://github.com/CeresDB/ceresdb/pull/538

**Comment by ShiKaiWi** [comment]
All the breaking changes we know are all finished.
