### ISSUE TITLE
Support limit the size of sst generated by compaction

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/ceresdb#408]
### Describe This Problem

Currently, it seems there is no limit on the sst size generated by the compaction procedure, that is to say, some huge sst files may occur. It is ok for the local file system, but it will cause some problems, including higher possibility of failure of downloading or uploading when using the remote object store as the underlying storage layer.

### Proposal

Firstly, we should make the sst size limit configurable. However, this is not enough to handle the case where the size of the compaction output is indeed larger than the limit. So I propose the compaction procedure should support multiple output files. After that, the very large output sst will be split to multiple small ssts.

**Comment by jiacai2050** [comment]
It seems #483 works well in prod, so closing this.
