### ISSUE TITLE
whether to need to adjust the `ArrowSchemaMetaKey: : NumKeyColumns`

### ISSUE THREAD

**Issue by dust1** [CeresDB/ceresdb#419]
### Describe This Problem

after the modification of #340 . 
The concept of `NumKeyColumns` is no longer important, so does it need to be changed when building arrow schema meta data here?
https://github.com/CeresDB/ceresdb/blob/c0f498bca3cf1efc36936ff3b591b7f22621ddbd/common_types/src/schema.rs#L1129-L1134

### Proposal

Maybe save the `primary_key_indexes`?

### Additional Context

This may run into serialization problems

**Comment by dust1** [comment]
maybe I can do this after another pr finish

**Comment by jiacai2050** [comment]
Sorry for my delay, assigned!

**Comment by ShiKaiWi** [comment]
I guess this issue has been solved by #526.
