### ISSUE TITLE
add mysql server support

### ISSUE THREAD

**Issue by dust1** [CeresDB/ceresdb#43]
**Description**

ceresdb doesn't seem to support mysql client yet

**Proposal**

we can use this crate solves that problem by acting as a MySQL server, and delegating operations such as querying and query execution to user-defined logic.

**Additional context**

https://github.com/jonhoo/msql-srv

**Comment by waynexia** [comment]
Greeting @dust1 🤗

Your proposal sounds really cool and feasible, do you want to elaborate/implement it? We are interested in this feature though it is not in our current plans. And we are happy to offer any level of assistance.

Please do let us know if this matches your interests as well!

**Comment by dust1** [comment]
@waynexia Thanks for taking my suggestion. I can try to implement it. I will try to submit a PR this weekend. I don't have much database experience, maybe need your help later.

**Comment by ShiKaiWi** [comment]
> @waynexia Thanks for taking my suggestion. I can try to implement it. I will try to submit a PR this weekend. I don't have much database experience, maybe need your help later.

No need to worry about it. Here are some suggestions I can provide:

**Comment by ShiKaiWi** [comment]
> @waynexia Thanks for taking my suggestion. I can try to implement it. I will try to submit a PR this weekend. I don't have much database experience, maybe need your help later.

No need to worry about it.🤗

Here are some suggestions I can provide before you starting:
- The mysql service may be set in the `Server` struct https://github.com/CeresDB/ceresdb/blob/dc9b2067330fcb1afb980195b21f7d9300c44306/server/src/server.rs#L64
- The implementation of the delegation may refer to the http service https://github.com/CeresDB/ceresdb/blob/dc9b2067330fcb1afb980195b21f7d9300c44306/server/src/http.rs#L95

**Comment by dust1** [comment]
@ShiKaiWi thanks, important suggestions for me!

**Comment by jiacai2050** [comment]
FYI, there is anther MySQL server wrapper:  https://github.com/datafuselabs/opensrv

It would be better you compare those two crates before you start, thanks.

**Comment by dust1** [comment]
> FYI, there is another MySQL server wrapper: https://github.com/datafuselabs/opensrv
> 
> It would be better you compare those two crates before you start, thanks.

get it!
