### ISSUE TITLE
Should we add `TimeWindowSized` compaction strategy?

### ISSUE THREAD

**Issue by chunshao90** [CeresDB/ceresdb#452]
### Describe This Problem

Currently, the compaction strategy adopts the TimeWindow strategy by default.
SST size can be up to GB. Performance may be better on local disk,
But in oss, will a certain size of sst achieve better performance, such as 200M?

### Proposal

Should we add `TimeWindowSized` compaction strategy?

**Comment by ShiKaiWi** [comment]
Firstly, I guess `TimeWindow` strategy with a new configuration for sst size threshold is enough. As for performance, I'm not sure about it and I guess we need real cases to tell us about it.

**Comment by jiacai2050** [comment]
This issue has been resolved in main.
