### ISSUE TITLE
Possible enhancements in first query

### ISSUE THREAD

**Issue by Rachelint** [CeresDB/ceresdb#467]
### Describe This Problem

The speed of first query in ceresdb with oss is acceptable now, but more enhancements can still be done.

### Proposal

- [x] Make mergeIterator initializing concurrently
  #466 
- [x] Make pulling sst from sst concurrently
- [ ] Get data after pulling from remote storage immediately rather than waiting until it is written to disk cache

**Comment by jiacai2050** [comment]
There are several TODO in disk_cache.rs now, fix them would address your second proposal.
- https://github.com/CeresDB/ceresdb/blob/505b9aca71ccc1ae0f120ef655509b85bfa89fce/components/object_store/src/disk_cache.rs#L132
- https://github.com/CeresDB/ceresdb/blob/505b9aca71ccc1ae0f120ef655509b85bfa89fce/components/object_store/src/disk_cache.rs#L175

**Comment by jiacai2050** [comment]
Closing since no obvious work need to be done now.
