### ISSUE TITLE
Reduce the memory consumption required by Compaction

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/ceresdb#489]
### Describe This Problem

Current compaction procedure consumes much more memory than expected. The theoretical usage of memory should be a little more than the total size of all the input ssts, but now the actual consumption is 4-10 times theoretical value.

### Proposal

The reasons for the high memory consumption, I can come up with these:
- #486
- The input data which will be invalidated later should be put back into the cache;
- Some indexes (e.g. bloom filter) are not necessary to be loaded because predicates won't be used by compaction.

**Comment by jiacai2050** [comment]
Fixed in main.
