### ISSUE TITLE
Is `analytic_engine` a proper name?

### ISSUE THREAD

**Issue by archerny** [CeresDB/ceresdb#497]
### Describe This Problem

For both traditional time-series workloads and analytic workloads, we use the component named `analytic_engine`. It seems not reasonable.

### Proposal

Rename it to `engine`

### Additional Context

no

**Comment by ShiKaiWi** [comment]
It does make senses.

Actually, this engine is initially designed for analytical workload. However, now it is expected to handle both time-series and analytical workload.

And maybe we can call it `MetricEngine`, and the multi-engine architecture may include `Log`, `Trace` engine in the future if possible.

**Comment by archerny** [comment]
As far as I can see, `Metric` is a domain specific concept. It fits well for scenarios in monitoring and IoT. However, there are plenty of other use cases, such as time-series analysis for stocks, bonds etc.

So, I'm considering changing it to a more general name.

BTW, there is another component named `query_engine`. Lots of engines 🐶
