### ISSUE TITLE
Add unit tests in avro.rs

### ISSUE THREAD

**Issue by chunshao90** [CeresDB/ceresdb#516]
### Describe This Problem

Missing unit tests in avro.rs.

### Proposal

Add some unit test in avro.rs.

**Comment by jiacai2050** [comment]
Do you think about encode/decode RecordBatch directly using https://docs.rs/arrow-ipc/30.0.0/arrow_ipc/index.html?

I think avro is not suitable for encode/decode RecordBatch, it may incur more cpu overhead than arrow-ipc.

**Comment by jiacai2050** [comment]
Avro is removed from our codebase
