### ISSUE TITLE
add new a target `make dev-setup` to install dependencies

### ISSUE THREAD

**Issue by dust1** [CeresDB/ceresdb#529]
### Describe This Problem

it just echo branch

### Proposal

Initialize the environment or install the necessary tools, e.g. `pkg-config`, `libssl-dev`.

**Comment by jiacai2050** [comment]
I think current usage is a convention, `init` is a common task(such as setting env vars) which others can depend on.

It should be light weighted, install dependencies is kinds of a heavy task, so it may not suit here.

**Comment by dust1** [comment]
Whether `ceresdb` will have commands to install dependencies in the future? e.g. `make setup`.
I recently used `ceresdb` in a new environment and would it be much easier to have such a command

**Comment by jiacai2050** [comment]
We can add new a target to install those dependencies. Example:

```
dev-setup:
  if macOS
    brew install protobuf
  if Ubuntu 
    sudo apt install --yes protobuf-compiler

```
