### ISSUE TITLE
Limit the number of columns in a table

### ISSUE THREAD

**Issue by chunshao90** [CeresDB/ceresdb#533]
### Describe This Problem

The number of columns in the table will affect the query write performance, we need to limit the number of columns.

### Proposal

Add a new parameter in config to limit the number of columns.

**Comment by jiacai2050** [comment]
It's awkward to add this limit to a column-based database, it should be optimized for table with wide columns.

I think a high level task is to investigate which part cause bottleneck, and try to fix them.
