### ISSUE TITLE
Delete `proto` dir and maintain pb in ceresdbproto

### ISSUE THREAD

**Issue by chunshao90** [CeresDB/ceresdb#571]
### Describe This Problem

Currently ceresdb `protobuf` is maintained in two places, one is https://github.com/CeresDB/ceresdbproto, and the other is https://github.com/CeresDB/ceresdb/tree/main/proto.
In the previous design, the `proto` dir in ceresdb ceresdb stored the pb used by the ceresdb server, but with more features developed, the `proto` and `ceresdbproto` would define the same elements, such as TableSchema and RequestHeader.

### Proposal

Delete `proto` dir and maintain pb in ceresdbproto.

**Comment by Rachelint** [comment]
Done
