### ISSUE TITLE
Store snapshot of manifest to object store

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/ceresdb#579]
### Describe This Problem

Currently, the snapshot and normal updates of manifest are appended to WAL, which leads to such problems:
- Complexity of processing the concurrent writing to WAL of snapshotting and normal updating;
- One giant snapshot may exceed the limit of the length of one WAL entry;

### Proposal

The basic idea of the proposal is simple: store the snapshot to the object store.

### Additional Context

This is a breaking change #402.

**Comment by ShiKaiWi** [comment]
Here is a diagram to describe the new storage of manifest combined with WAL and Object Storage
```
                      ┌─────────────────────────────────────────────────────────────────┐ 
                      │                                                                 │ 
                      │    ┌────────┐                                                   │ 
                      │    │    3   │  /manifest/snapshot/{space_id}/{table_id}/current │ 
┌──────┐              │    └────────┘                                                   │ 
│  4   │              │         │                                                       │ 
├──────┘              │         │                                                       │ 
   3   │─────────┐    │         ▼                                                       │ 
├ ─ ─ ─          │    │    ┌────────┐                                                   │ 
   2   │─────────┼────┼───▶│Snapshot│     /manifest/snapshot/{space_id}/{table_id}/3    │ 
├ ─ ─ ─          │    │    └────────┘                                                   │ 
   1   │─────────┘    │                                                                 │ 
└ ─ ─ ─               └─────────────────────────────────────────────────────────────────┘ 
                                                                                          
  WAL                                          Object Storage                             
                                                                                          
```

**Comment by jiacai2050** [comment]
> Overwrite the /manifest/snapshot/{space_id}/{table_id}/current to map the current snapshot to the path of the latest snapshot;

How will you ensure this operation is atomic?

**Comment by ShiKaiWi** [comment]
> > Overwrite the /manifest/snapshot/{space_id}/{table_id}/current to map the current snapshot to the path of the latest snapshot;
> 
> How will you ensure this operation is atomic?



> > Overwrite the /manifest/snapshot/{space_id}/{table_id}/current to map the current snapshot to the path of the latest snapshot;
> 
> How will you ensure this operation is atomic?

I guess the `ObjectStore` trait should ensure that operation to be atomic.

Currently, for the real object storage service, e.g. AWS3, Aliyun OSS, the consistency model guarantees the put/update is atomic. As for the current "object store" based local file system in CeresDB, the atomic put/update is actually not ensured yet, but I guess it should provide such guarantee to meet the requirements by the `ObjectStore` trait.
