### ISSUE TITLE
Query fields are sorted by creation

### ISSUE THREAD

**Issue by dust1** [CeresDB/ceresdb#60]
**Description**
ceresDB doesn't seem to require strict ordering of query result fields.

**Proposal**

Use the order in which fields are created.

**Additional context**

when I create table use: 
```
CREATE TABLE `hello_mysql` (`name` string TAG, `value` double NOT NULL, `t` timestamp NOT NULL, TIMESTAMP KEY(t)) ENGINE=Analytic with (enable_ttl='false');
```
and select it. his field order seems to be random? I found that the query result is wrapped in HashMap.
![image](https://user-images.githubusercontent.com/18304424/175182397-bf4b73ce-8cc2-4e44-9dda-d97ba4992267.png)

This doesn't seem to have any effect on normal usage, so I don't know if this situation needs improvement.

**Comment by dust1** [comment]
> AFAIK, most databases don't support strict ordering of query result unless specified by `ORDER BY`.
> 
> * https://stackoverflow.com/questions/8746519/sql-what-is-the-default-order-by-of-queries

ORDER BY should be the result of the query, I mean the order of the fields in the query rather than the order of the data.
The order of fields I specified in `CREATE TABLE` is: `name`, `value`, `t` and `tsid`. do we need to follow this order when returning query results, His current order is: `value`, `tsid`, `name` and `t`

**Comment by jiacai2050** [comment]
Sorry missing that.

I think query result should match the column ordering when created, I'm a little annoyed with this recently.

```
{
  "rows": [
    {
      "tsid": 18356650801274184101,
      "timestamp": 1655693797000,
      "value": 1.0,
      "ip": "1",
      "dc": "lgab"
    },
    {
      "value": 2.0,
      "ip": "1",
      "timestamp": 1655693798000,
      "dc": "lgab",
      "tsid": 18356650801274184101
    }
  ]
}
```
As you can see above, it a little hard to read `value` column as it appears in different locations.

**Comment by dust1** [comment]
Maybe we can replace HashMap with another data structure https://github.com/datafuselabs/databend/blob/main/common/datablocks/src/data_block.rs#L29
But I haven't understood the storage principle of ceresdb in detail.😂 I don't know what this modification will involve.

**Comment by waynexia** [comment]
Replace hashmap will not infect the storage layer. Query result is ordered until https://github.com/CeresDB/ceresdb/blob/2fda373f49b17269464afe41b275fcf0ca2cc497/server/src/handlers/sql.rs#L118-L123

`Response`:
https://github.com/CeresDB/ceresdb/blob/2fda373f49b17269464afe41b275fcf0ca2cc497/server/src/handlers/sql.rs#L30-L35

There may have two steps of this change I think:
 - Change `convert_output` and  `Response`, replace that hashmap to something like
```rust
struct Rows {
    column_names: Vec<String>,
    data: Vec<Vec<Datum>>,
}
```
- HTTP interface still returns the map above (but keeps ordering). So we need to change the serialize method of the new `Response`.

**Comment by waynexia** [comment]
BTW we can do this in the subsequent PR, #56 needs not to include this😼

**Comment by dust1** [comment]
Yes, I stumbled across it last night while testing, so filed an issue. 😂

**Comment by dust1** [comment]
hello @jiacai2050 ,Are you dealing with this issue now? if there is not, can I try do this?
