### ISSUE TITLE
Use column id instead of index to refer column when persist to storage

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/ceresdb#616]
### Describe This Problem

When persist schema info, we use column index to refer corresponding column, this works fine if schema is not updated, and will block us to implement some DDL, such as add column after another.

### Proposal

Use column id to refer column when need to persist to underlying storage.

### Additional Context

AFAIK, primary keys/bloom filters in encoded using index now.

**Comment by ShiKaiWi** [comment]
Assuming that **schema info** mentioned here is the one in the SST, I guess this is not necessary, because the existing sst won't be updated even if the schema is updated.

**Comment by jiacai2050** [comment]
I grep TableSchema, schema is not only used in SST, but also in meta_update.

```
7 candidates:
./common.proto:46:message TableSchema {
./common.proto:67:  common.TableSchema table_schema = 1;
./meta_update.proto:43:  common.TableSchema schema = 4;
./meta_update.proto:98:  common.TableSchema schema = 3;
./remote_engine.proto:64:  common.TableSchema table_schema = 1;
./sst.proto:34:  common.TableSchema schema = 5;
./table_requests.proto:14:  common.TableSchema schema = 2;
```
