### ISSUE TITLE
Supports automatic field creation

### ISSUE THREAD

**Issue by jiwliu** [CeresDB/ceresdb#634]
### Describe This Problem

When ceresdb writes data for the first time, it supports automatic table creation, but when the data written next contains new fields, it does not support automatic creation of new fields. It is hoped that new fields can be automatically created in this scenario

### Proposal

Supports automatic field creation

**Comment by jiacai2050** [comment]
This sounds a good feature. 

A pre-task of this feature is to support alter table schema, I will create another issue to track this.
