### ISSUE TITLE
How about using the struct defined in proto directly?

### ISSUE THREAD

**Issue by Rachelint** [CeresDB/ceresdb#638]
### Describe This Problem

When using the struct defined in proto, we will define a struct with same fields and convert the proto one to it.

It make sense before replacing the proto processing crate from `grpcio`'s to `tonic`'s, becasue it is hard to do this with the one in `grpcio`.

However, it is so convenient to do this now. 

### Proposal

Directly use the struct defined in proto.

**Comment by jiacai2050** [comment]
For simple case, I think we can re-export types defined in proto.

However, types defined in proto may not what we want in upper layer, for example 
```rs
pub space_id: SpaceId,
pub table_id: TableId,
```
We have type alias for table_id and space_id, but in proto those fields are all u64, so in this case a mapping is required.

**Comment by ShiKaiWi** [comment]
Besides the problem mentioned by @jiacai2050, another dilemma is that the custom structs generated by `prost` are always wrapped in an `Option`, which may be very inconvenient for use.

**Comment by Rachelint** [comment]
> Besides the problem mentioned by @jiacai2050, another dilemma is that the custom structs generated by `prost` are always wrapped in an `Option`, which may be very inconvenient for use.

Yes, the nested or oneof struct has this problem...
