### ISSUE TITLE
Formatter can't recognize newline missing

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/ceresdb#65]
**Description**
Now the rust formatter can't recognize the necessary newline missing, e.g.:
```rust
use crate::{
    instance::{Instance, InstanceRef},
    mysql::{error::*, worker::MysqlWorker},
};
pub struct MysqlService<C, Q> {
```

Make the formatter can fix this case.

**Proposal**
No proposal yet.

**Additional context**

**Comment by jiacai2050** [comment]
There is a tracking issue in rustfmt:
- https://github.com/rust-lang/rustfmt/issues/3382

**Comment by waynexia** [comment]
current version of `blank_lines_lower_bound` is not what we want: https://rust-lang.github.io/rustfmt/?version=v1.5.0&search=#blank_lines_lower_bound

its example behavior is a bit wired
```rust
fn foo() {

    println!("a");
}

fn bar() {

    println!("b");

    println!("c");
}
```

**Comment by jiacai2050** [comment]
> current version of blank_lines_lower_bound is not what we want

[This comment](https://github.com/rust-lang/rustfmt/issues/3382#issuecomment-864698337) says it's already been fixed in this https://github.com/rust-lang/rustfmt/pull/4295, just not released...

**Comment by ygf11** [comment]
I think [`rust-lang/rustfmt#4295`](https://github.com/rust-lang/rustfmt/pull/4295) is merged to the `rustfmt-v2-rc` branch, which is not going to release.

So the current release(`rustfmt-v1`) does not contain this patch.

`rustfmt-v2` tracking issue:
 rust-lang/rustfmt#3887

**Comment by jiacai2050** [comment]
Closing since this won't be fix with rustfmt-v1
