### ISSUE TITLE
Failed to write data through HTTP interface.

### ISSUE THREAD

**Issue by ZuLiangWang** [CeresDB/ceresdb#654]
### Describe this problem

I try to execute insert request by HTTP interface:
```
curl --location --request POST 'http://127.0.0.1:5440/sql' \
--data-raw '
INSERT INTO `02_function_thetasketch_distinct_table`
(`timestamp`, `arch`, `datacenter`, `value`)
VALUES
    (1658304762, 'x86', 'china', 75)
'
```
And it will throw an error:
```
{"code":500,"message":"Failed to handle request, err:Failed to create plan, query:\nINSERT INTO `02_function_thetasketch_distinct_table`\n(`timestamp`, `arch`, `datacenter`, `value`)\nVALUES\n    (1658304762, x86, china, 75)\n, err:Failed to create plan, err:Invalid insert stmt, source expr is not value, source_expr:Identifier(Ident { value: \"x86\", quote_style: None })."}%
```
But when I try to same sql though grpc request, it will work normally.
I guess there is a problem with the data parsing of the HTTP request.

### Steps to reproduce

curl --location --request POST 'http://127.0.0.1:5440/sql' \
--data-raw '
CREATE TABLE `02_function_thetasketch_distinct_table` (
    `timestamp` timestamp NOT NULL,
    `arch` string TAG,
    `datacenter` string TAG,
    `value` int,
    timestamp KEY (timestamp)) ENGINE=Analytic
WITH(
	 enable_ttl='false'
);
'

curl --location --request POST 'http://127.0.0.1:5440/sql' \
--data-raw '
INSERT INTO `02_function_thetasketch_distinct_table`
(`timestamp`, `arch`, `datacenter`, `value`)
VALUES
    (1658304762, 'x86', 'china', 75)
'

### Additional Information
```
curl --location --request POST 'http://127.0.0.1:5440/sql' \
--data-raw '
INSERT INTO `02_function_thetasketch_distinct_table`
(`timestamp`, `arch`, `datacenter`, `value`)
VALUES
    (1658304762, "x86", "china", 75)
'
```
The string enclosed by double quotation marks can be written normally.

**Comment by jiacai2050** [comment]
It seems you have used mixed single quote, try this

```curl
curl --location --request POST 'http://127.0.0.1:5440/sql' \
--data-raw "
INSERT INTO `02_function_thetasketch_distinct_table`
(`timestamp`, `arch`, `datacenter`, `value`)
VALUES
    (1658304762, 'x86', 'china', 75)
"
```
