### ISSUE TITLE
Support show database show tables

### ISSUE THREAD

**Issue by chunshao90** [CeresDB/ceresdb#66]
**Description**

support `show database` and `show tables`

**Proposal**

**Additional context**

**Comment by dust1** [comment]
does ceresdb support `create database`? Sorry I can't test it right now, but there is no relevant sql example in README.md

**Comment by ShiKaiWi** [comment]
Actually, `database` is called `schema` in ceresdb and now it can't be created dynamically and can only be configured statically.

**Comment by ShiKaiWi** [comment]
> does ceresdb support `create database`? Sorry I can't test it right now, but there is no relevant sql example in README.md

Actually, database is called schema in ceresdb and now it can't be created dynamically and can only be configured statically.

**Comment by dust1** [comment]
> Actually, database is called schema in ceresdb and now it can't be created dynamically and can only be configured statically.

Thanks for your answer, maybe I can do this issue, can you assign it to me?
