### ISSUE TITLE
Does ceresDB support prometheus remote_write data input ?

### ISSUE THREAD

**Issue by Buddruggy** [CeresDB/ceresdb#67]
**Description**

Does ceresDB support prometehus remote_write data input?

https://prometheus.io/docs/prometheus/latest/configuration/configuration/?spm=a2c63.p38356.0.0.1c73743dfdpdeF#remote_write

**Proposal**

**Additional context**

**Comment by chunshao90** [comment]
We are considering implementing CeresDB as Prometheus remote storage. @waynexia will provide an RFC.

**Comment by waynexia** [comment]
I'm drafting a proposal but it's mainly about remote read. Writable storage may come later. Though it's not planned in present, it should not be very different from the read path.

**Comment by Buddruggy** [comment]
> I'm drafting a proposal but it's mainly about remote read. Writable storage may come later. Though it's not planned in present, it should not be very different from the read path.

OK, thanks for reply! 

And i have another question about the performance about ceresDB, Is there a performance test report comparing influxDB /clickhouse/druid...?

**Comment by jiacai2050** [comment]
Hi, the project is still in rapid development, so we haven't done much benchmark work. 

BTW, I would like to know what features do you care most for a Prometheus remote storage?

**Comment by Buddruggy** [comment]
> Hi, the project is still in rapid development, so we haven't done much benchmark work.
> 
> BTW, I would like to know what features do you care most for a Prometheus remote storage?

OK,  i see.

For a prometheus storage, the most thing i care about is the performance, And can be compatible with prometheus query and write protocol.
