### ISSUE TITLE
Make integration tests easier to run locally

### ISSUE THREAD

**Issue by chunshao90** [CeresDB/ceresdb#675]
### Describe This Problem

Running integration tests locally requires too many preconditions.
* Add ceresdb*ceresmeta in `/etc/hosts`.
* Install docker compose.
* Build docker image.
* Modify docker compose config.
* Configuration files are scattered in several places.

### Proposal

Complete manual operations in one step with scripts.

**Comment by jiacai2050** [comment]
Another choice is for integration test to allow run local(or cluster) test only.

**Comment by chunshao90** [comment]
#740
