### ISSUE TITLE
Tracking issue: InfluxQL support

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/ceresdb#682]
### Describe This Problem

InfluxQL is widely used in the timeseries DBMS field, and CeresDB should support such a protocol for integration into the ecosystem.

### Proposal

The work includes three parts:
- Write: the parser of line protocol;
- Query: 
  - The parser for InfluxQL;
  - The planner for InfluxQL;

**Comment by Rachelint** [comment]
Works of query part may can be divided into three part:
+ Support statements compatible with sql statmens (may be need some rewrites)
   + Wildcard and regrex in select fields, from clause, group by clause.
   + From multiple tables.
+ Support statements can be represent by `udf`
   + Selector aggregate function.
   + Some special udf.
+ Support statemetns only can be represent by `extension logical node`
   + Some special clause, such as slimit clause, soffset clause, fill clause.

**Comment by ShiKaiWi** [comment]
In favor of #698
