### ISSUE TITLE
Should CeresDB support interface route in No-Meta mode?

### ISSUE THREAD

**Issue by MachaelLee** [CeresDB/ceresdb#702]
### Describe This Problem

In With-Meta mode, We can use route interface to query table's location as follow:
```
curl --location --request POST 'http://{CeresMetaAddr}:8080/api/v1/route' \
--header 'Content-Type: application/json' \
--data-raw '{
    "clusterName":"defaultCluster",
    "schemaName":"public",
    "table":["demo"]
}'

```

But there is no one in No-Meta mode.

### Proposal

Should we support interface route in No-Meta mode?

**Comment by ShiKaiWi** [comment]
Duplicate of #146

**Comment by ShiKaiWi** [comment]
Duplicate of #146

**Comment by MachaelLee** [comment]
> If #146 fixed, we can retrieve routing information from CeresDB rather than CeresMeta no matter which mode is chosen.

Yes, I think it is more reasonable to retrieve routing information from CeresDB. It is not necessary for users to be aware of Meta.
