### ISSUE TITLE
Define Error as associate type in WalManager

### ISSUE THREAD

**Issue by chunshao90** [CeresDB/ceresdb#71]
**Description**
define Error as associate type in WalManager

**Proposal**
source code：
https://github.com/CeresDB/ceresdb/blob/1e2e0b362b1d3afb3cef5350adb8dd5118db3e28/wal/src/manager.rs#L260
refer to: https://github.com/CeresDB/ceresdb/blob/839948bd6a551f4af35246eba01ad30d5e773ddd/analytic_engine/src/memtable/key.rs#L118

**Additional context**

**Comment by dust1** [comment]
can this be assigned to me?

**Comment by ShiKaiWi** [comment]
> can this be assigned to me?

Sure! Just pay attention to that [this issue](https://github.com/CeresDB/ceresdb/issues/72#issuecomment-1181427851) may refactor the `WalManager` at the same time.

**Comment by waynexia** [comment]
Close as discussed in https://github.com/CeresDB/ceresdb/pull/106#issuecomment-1188504653
