### ISSUE TITLE
Support PostgreSQL wire protocol

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/ceresdb#711]
### Describe This Problem

MySQL wire protocol is already supported by CeresDB, it would be great to support PostgreSQL also.

### Proposal

Support PostgreSQL protocol like MySQL

### Additional Context

https://github.com/sunng87/pgwire

**Comment by holicc** [comment]
i'd like to do this, but i'm new to rust, can i take this ?

**Comment by jiacai2050** [comment]
Thanks for you interests, let us know when you have any trouble.

You can refer how MySQL is implemented.
https://github.com/CeresDB/ceresdb/blob/ee10f2f8f84fd75c6f680c34c2f2f15dc59eed4e/server/src/mysql/service.rs#L15

**Comment by holicc** [comment]
I found something confused:

```sql 
CREATE TABLE `demo`(`name`string TAG,`id` int TAG,`value` double NOT NULL,`t` timestamp NOT NULL,TIMESTAMP KEY(t)) ENGINE = Analytic with(enable_ttl=false);

insert into demo (name,value,t)values("ceresdb",1,1691116127622);
```

When i try to insert value with column `t`, ceresDB treat `t` as `UInt64(12128845460635970325)`.  Shouldn't it be a `Timestamp` type ?

**Comment by jiacai2050** [comment]
@holicc  This is what I got by `select * from demo;`;
```
tsid	t	name	id	value
12128845460635970325	1691116127622	ceresdb	NULL	1
```
`12128845460635970325 ` is `tsid`, not `t`.

**Comment by holicc** [comment]
@jiacai2050 Sorry, my bad. But PostgreSQL doesn't support unsigned int yet. Can i just cast uint to int ?
