### ISSUE TITLE
'Table is not found ' in PartitionTable

### ISSUE THREAD

**Issue by zouxiang1993** [CeresDB/ceresdb#771]
### Describe this problem

Error message is:
```
{"code":500,"message":"Failed to handle request, err:Failed to execute interpreter, query:\nselect count(*) from perflog\n, err:Failed to execute select, err:Failed to execute logical plan, err:Failed to collect record batch stream, err:Stream error, msg:convert from arrow record batch, err:External error: Stream error, msg:poll read response failed, err:Failed to query from table in server, table_ident:TableIdentifier { catalog: \"ceresdb\", schema: \"public\", table: \"__perflog_1\" }, code:404, msg:table is not found, table:__perflog_1"}
```

### Server version

CeresDB Server
CeresDB version: 1.0.0
Git branch: main
Git commit: https://github.com/CeresDB/ceresdb/commit/95ea87054a940ba830973aba58e8476479d23680
Build time: 2023-03-06T03:30:09.845055021Z
Rustc version: 1.69.0-nightly

### Steps to reproduce

1. create a partition table : CREATE TABLE perflog (...) PARTITION BY KEY(host) PARTITIONS 10
2. DROP TABLE perflog
3. create the same table with a different partition number: CREATE TABLE perflog (...) PARTITION BY KEY(host) PARTITIONS 128
4. SELECT count(*) FROM xxx. Query fails, the error message is mentioned above.

**Comment by ShiKaiWi** [comment]
@chunshao90 Would you like to help troubleshoot this problem? I guess the table partitioning has not been fully supported yet.

**Comment by chunshao90** [comment]
Is there any error during the table creation process?
I cannot reproduce the error locally. Two `ceresdb-server` with one `ceresmeta-server`.

**Comment by chunshao90** [comment]
This issue may be caused by ceresmeta.
Refer to https://github.com/CeresDB/ceresmeta/issues/152。

**Comment by ShiKaiWi** [comment]
Fixed already.
