### ISSUE TITLE
Integration test framework

### ISSUE THREAD

**Issue by waynexia** [CeresDB/ceresdb#83]
**Description**

Provides a test framework to make us easy to write integration tests at SQL level.

**Proposal**

I plan to write this in python. It should be able to start server with special (non-default) configs, execute SQL and compare the result. Configuration, input data, SQL and expected output can be put in other text files.

**Additional context**

Other systems' framework:
- [MariaDB](https://github.com/MariaDB/server/blob/10.10/mysql-test/README)
- [Databend](https://github.com/datafuselabs/databend/blob/main/tests/README.md)
- [ClickHouse](https://github.com/ClickHouse/ClickHouse/blob/master/tests/clickhouse-test)
- [InfluxDB IOx](https://github.com/influxdata/influxdb_iox/blob/main/query_tests/README.md)

**Comment by ShiKaiWi** [comment]
I'm OK with python but maybe Rust is a better choice.

**Comment by jiacai2050** [comment]
IMO, Go/Rust is preferred over others, unless it has obvious advantages.

**Comment by waynexia** [comment]
👍  I'll check it. I chose python for convenience at first
