### ISSUE TITLE
Tracking issue for influxql support

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/ceresdb#830]
### Describe This Problem

After #824, influxql support is almost finished, users can query ceresdb via influxdb datasource in grafana. 

This issue track some improvements:

- [x] In InfluxQLSchemaProvider we hold all tables in HashMap, this is expensive and in theory we could load tables in lazy way.
- [x] Currently depend on iox directly, maybe we could extract them to https://github.com/CeresDB/influxql, or better to contribute to iox project.

### Proposal

See above.

**Comment by Rachelint** [comment]
All task finished, close it until new tasks came.
