### ISSUE TITLE
Affected rows reports wrong number for create/drop statements

### ISSUE THREAD

**Issue by waynexia** [CeresDB/ceresdb#87]
**Describe this problem**

```plaintext
Failed to execute query, err: Server(ServerError { code: 500, msg: "Failed to convert output, query: DROP TABLE demo;. Caused by: Rpc error, code:500, message:Failed to convert output - affected rows: 1" })
```
A drop table tells one row is affected

**Steps to reproduce**

```
drop table demo;
```

**Expected behavior**

```
mysql> create table xx like meta_2 ;
Query OK, 0 rows affected (0.11 sec)
```

**Additional Information**

These SQLs don't actually count rows, 1 is the default value. Change the default value should fix this.

**Comment by dust1** [comment]
can this be assigned to me? this looks like I didn't set it up before

**Comment by waynexia** [comment]
Thanks for your interest! This is an existing behavior. There are some places that are designed to act like this. E.g: https://github.com/CeresDB/ceresdb/blob/ddaa3e8346d14bcc4432a4b3ac24a28e316d42ca/table_engine/src/table.rs#L445-L454

**Comment by dust1** [comment]
It looks like I need to modify the implementation of the `Table` trait so that it defaults to 0?👀

**Comment by dust1** [comment]
ok i'll check it.
