### ISSUE TITLE
Extend `QueryResponse` to support "Affected Rows"

### ISSUE THREAD

**Issue by waynexia** [CeresDB/ceresdb#89]
**Description**

Our `QueryResponse` message doesn't support to pass how many rows are affected to the client.
```protobuf
message QueryResponse {
  common.ResponseHeader header = 1;
  enum SchemaType {
    AVRO = 0;
    JSON = 1;
  }
  SchemaType schema_type = 2;
  string schema_content = 3;
  repeated bytes rows = 4;
}
```

For some statements like INSERT/DELETE this is very useful. MySQL has a document about this https://dev.mysql.com/doc/c-api/8.0/en/mysql-affected-rows.html

>[mysql_affected_rows()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-affected-rows.html) may be called immediately after executing a statement with [mysql_real_query()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-real-query.html) or [mysql_query()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-query.html). It returns the number of rows changed, deleted, or inserted by the last statement if it was an [UPDATE](https://dev.mysql.com/doc/refman/8.0/en/update.html), [DELETE](https://dev.mysql.com/doc/refman/8.0/en/delete.html), or [INSERT](https://dev.mysql.com/doc/refman/8.0/en/insert.html). For [SELECT](https://dev.mysql.com/doc/refman/8.0/en/select.html) statements, [mysql_affected_rows()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-affected-rows.html) works like [mysql_num_rows()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-num-rows.html).

**Proposal**

Add a field in `QueryResponse` to tell how many rows are affected. Consider this also used by SELECT which won't "affect" rows, I propose this field can be called `row_count`.

**Additional context**

**Comment by ShiKaiWi** [comment]
`affected_rows` seems better and it can be set 0 for `SELECT` statement.

**Comment by waynexia** [comment]
> `affected_rows` seems better and it can be set 0 for `SELECT` statement.

`SELECT` can return the actual count and we don't need special logic for it. like 
>For [SELECT](https://dev.mysql.com/doc/refman/8.0/en/select.html) statements, [mysql_affected_rows()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-affected-rows.html) works like [mysql_num_rows()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-num-rows.html).

But this info can be retrieved by counting the data.

**Comment by ShiKaiWi** [comment]
It seems weird that `affected_rows` is actually`num_rows` for SELECT statement. On the other hand, `row_count` is not verbose enough for `INSERT` or `DELETE`. 

Maybe no need to keep the same meaning of `affected_rows` with mysql?

**Comment by waynexia** [comment]
Makes sense. Try to conclude:
- add a field named `affected_rows` to pb
- `affected_rows` is always set to the number of "affected" rows. 
  - `CREATE` affects 0 row
  - `INSERT` or `DELETE` affects the rows added or removed
  - `SELECT affects 0 row
