### ISSUE TITLE
Improve PQL regex query performance

### ISSUE THREAD

**Issue by chunshao90** [CeresDB/ceresdb#898]
### Describe This Problem

The following regex query is very slow.
```
sum (rate(http_requests_counter{url=~"/api/query|/plugin/prometheus/api/v1/query.*"}[3m])) 
```

But the performance is very good after splitting the query.
```
sum (rate(http_requests_counter{url="/plugin/prometheus/api/v1/query"}[3m])) 
sum (rate(http_requests_counter{url="/api/query"}[3m])) 
```

### Proposal

Improve PQL regex query performance.

**Comment by jiacai2050** [comment]
I think we can add a datafusion [OptimizerRule](https://docs.rs/datafusion-optimizer/25.0.0/datafusion_optimizer/optimizer/trait.OptimizerRule.html) to convert regex filter to equal filter, eg: `a=~"1|2"` could be converted to `a in (1, 2)`

**Comment by jiacai2050** [comment]
https://crates.io/crates/regex-syntax

This crate allow us to program based on regex syntax.

**Comment by tanruixiang** [comment]
https://github.com/apache/arrow-datafusion/pull/6487 partially solved the problem.

**Comment by tanruixiang** [comment]
https://github.com/apache/arrow-datafusion/issues/7185 Now we can support string which include `_`.
