### ISSUE TITLE
Use partitioned lock to optimize disk cache

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/ceresdb#914]
### Describe This Problem

Partitioned lock is a common trick to reduce lock contention, disk cache could use it to improve perf.

https://github.com/CeresDB/ceresdb/blob/da6899c4c97089d4fbd8aa8a01db98ab8366d5bc/components/object_store/src/disk_cache.rs#L114

### Proposal

Use PartitionedRwLock to replace `cache` in `DiskCache`

https://github.com/CeresDB/ceresdb/blob/da6899c4c97089d4fbd8aa8a01db98ab8366d5bc/common_util/src/partitioned_lock.rs#L17

**Comment by tanruixiang** [comment]
please assign to me.
