### ISSUE TITLE
Shard lock won't be released after open failure

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/ceresdb#916]
### Describe this problem

The shard lock won't be released after open failure.

### Server version

dcae0e086a8406ea57c36887eabf7ac27eb5ae4d

### Steps to reproduce

- Connect to the CeresMeta;
- When ceresdb receives an open shard request, it fails to open shard;
- The shard lock won't be released after that, that is to say, the shard won't be able to be opened any more.

### Expected behavior

The shard lock should be released if failed to open shard totally.

**Comment by jiacai2050** [comment]
Already fixed in https://github.com/CeresDB/ceresdb/pull/1104
