### ISSUE TITLE
Build guidance for mac users

### ISSUE THREAD

**Issue by archerny** [CeresDB/ceresdb#96]
**Description**

The doc now have no guidance for different platforms

**Proposal**

The project docs now don't have any build guidance for different platforms other than Ubuntu. We can add these docs to help the users solving problems when they build on their own dev env.

**Comment by tianlinzx** [comment]
Yes, we need detailed guidance how to build on Mac.

**Comment by tianlinzx** [comment]
1、xcode-select --install
2、brew install cmake
3、cargo build --release

**Comment by tianlinzx** [comment]
#169 is Submitted.
